#!/usr/bin/env -S -i dash
export PATH=../bin:/bin:/usr/bin
export TERM=xterm-256color
set -eu
clear

./Tbase64.moon
echo " base64 module tested."
sleep 2
clear

./Tcsv.moon
echo " ftcsv module tested."
sleep 2
clear

./Tescape_sql.moon
echo " lib.exec.escape_sql function tested."
sleep 2
clear

./Tjson.moon
echo " lunajson module tested."
sleep 2
clear

./Tlhutil.moon
echo " lua-http/util tested."
sleep 2
clear

./Tsqlite3.moon
echo " LJSQLite3 module tested."
sleep 2
clear

./stdin.sh
echo " STDIN to script tested."
sleep 2
clear

./Tuuid.moon
echo " uuid module tested."
sleep 2
clear

./Tcurler.moon
echo " curler module tested."
sleep 2
clear

./Tetlua.moon
echo " etlua module tested."
sleep 2
clear

moon moonscript/* && { echo "Ok."; }
echo " Partial MoonScript language tests done."
sleep 2
clear

./Tmoon_module.moon
echo " MoonScript module tested."



